/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package treeApp;

import javax.swing.UIManager;

/**
 *
 * @author Diego Geremia
 */
public class TreeApp extends javax.swing.JFrame {
    private Tree tree;
    /**
     * Creates new form TreeApp
     */
    public TreeApp() {
        initComponents();
        setSize(500,380);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        outputIn = new javax.swing.JTextField();
        outputSu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        input.setText("+ 3 7");
        getContentPane().add(input);
        input.setBounds(10, 30, 475, 20);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(205, 60, 85, 23);

        jLabel1.setText("Prefix Expression:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 14);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 90, 475, 190);
        getContentPane().add(outputIn);
        outputIn.setBounds(60, 290, 424, 20);
        getContentPane().add(outputSu);
        outputSu.setBounds(60, 320, 424, 20);

        jLabel2.setText("Sufix");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 320, 80, 20);

        jLabel3.setText("Infix");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 290, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input_str = input.getText();
        tree = new Tree(input_str);
        
        outputIn.setText(tree.getInExpression());
        outputSu.setText(tree.getPostExpression());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try{ UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); }
        catch(Exception ex){ }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreeApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField outputIn;
    private javax.swing.JTextField outputSu;
    // End of variables declaration//GEN-END:variables
}
